In [9]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y*y*2
#z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)


tensor([-0.0491,  1.6252,  1.1980], requires_grad=True)
tensor([1.9509, 3.6252, 3.1980], grad_fn=<AddBackward0>)
tensor([ 7.6117, 26.2843, 20.4547], grad_fn=<MulBackward0>)
tensor([7.8034e-01, 1.4501e+01, 1.2792e-02])


In [11]:
x = torch.randn(3, requires_grad=True)
print(x)

#disable grad tracking
#x.requires_grad_(False)
#x.detach()
#with torch.no_grad()

x.requires_grad_(False)
print(x)

y = x.detach()
print(y)

with torch.no_grad():
  y = x + 2
  print(y)


tensor([-0.7191,  0.3743,  0.1964], requires_grad=True)
tensor([-0.7191,  0.3743,  0.1964])
tensor([-0.7191,  0.3743,  0.1964])
tensor([1.2809, 2.3743, 2.1964])


In [15]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()