In [4]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.1987, 0.3057],
        [0.4937, 0.6043]])

In [8]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeroes_tensor

(tensor([[0.2855, 0.8790, 0.6827],
         [0.4092, 0.4634, 0.7725]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [9]:
tensor = torch.rand(3, 4)
tensor.dtype, tensor.shape, tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

In [10]:
!nvidia-smi

Mon Aug 12 15:18:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [11]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [12]:
tensor = torch.ones(4, 4)
print("First row:", tensor[0])
print("First column:", tensor[:, 0])
print("Last column:", tensor[:, -1])
tensor[:, -1] = -1
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[ 1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.]])


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[ 1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.]])

In [16]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

y1, y2, y3

(tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]),
 tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]),
 tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]))

In [17]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

z1, z2, z3

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [20]:
agg = tensor.sum()
agg_item = agg.item()
agg, type(agg_item)

(tensor(8.), float)

In [21]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[ 1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.],
        [ 1.,  1.,  1., -1.]]) 

tensor([[6., 6., 6., 4.],
        [6., 6., 6., 4.],
        [6., 6., 6., 4.],
        [6., 6., 6., 4.]])


In [22]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [23]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [24]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
n, t

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))