In [2]:
import torch

x = torch.rand(2, 2)
y = torch.rand(2, 2)

z = x + y
print(z)
z = torch.add(x, y)
print(z)
y.add_(x)
print(y)

#the same with subtraction, multiplication and division



tensor([[0.2779, 0.2877],
        [0.7140, 1.2786]])
tensor([[0.2779, 0.2877],
        [0.7140, 1.2786]])
tensor([[0.2779, 0.2877],
        [0.7140, 1.2786]])


In [4]:
x = torch.rand(5, 3)
print(x[:])
print(x[:0])
print(x[1, :])
print(x[1, 1].item())

tensor([[0.6904, 0.0346, 0.1997],
        [0.6996, 0.7176, 0.2691],
        [0.2365, 0.0658, 0.8641],
        [0.7092, 0.5367, 0.4107],
        [0.7293, 0.2384, 0.6316]])
tensor([], size=(0, 3))
tensor([0.6996, 0.7176, 0.2691])
0.7176359295845032


In [5]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[0.5515, 0.1046, 0.8395, 0.8382],
        [0.3153, 0.5824, 0.6036, 0.0624],
        [0.1649, 0.8748, 0.7947, 0.5383],
        [0.5009, 0.0769, 0.7209, 0.8488]])
tensor([0.5515, 0.1046, 0.8395, 0.8382, 0.3153, 0.5824, 0.6036, 0.0624, 0.1649,
        0.8748, 0.7947, 0.5383, 0.5009, 0.0769, 0.7209, 0.8488])


In [9]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [11]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [13]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to("cpu")

In [14]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
